<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip</name>
   <tag></tag>
   <elementGuidId>16a44219-2eef-4c56-b92d-bf597e0fb952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question_1000139113']/span/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ss-skip-action-btn.ss-survey-font-family.ss-survey-text-size--sm.ss-survey-line-height--none.ss-survey-text-weight--bold.ss-survey-text-color--primary-04</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a95642c-c8ad-4d10-a00c-e01385edbafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>skip_button</value>
      <webElementGuid>c172b653-4b4d-4db8-9e24-a2920e0f3ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hotkey-item</name>
      <type>Main</type>
      <value>hotkey-skip-button</value>
      <webElementGuid>fbcd0d3a-884a-466d-9df0-ae734c2b78c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-skip-action-btn ss-survey-font-family ss-survey-text-size--sm ss-survey-line-height--none ss-survey-text-weight--bold ss-survey-text-color--primary-04</value>
      <webElementGuid>8ee448cf-56e7-468b-be97-c855040d188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>178c0a2f-2c81-47ab-a941-bf67431bc24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000139113&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_cl_qstn_action&quot;]/div[@class=&quot;ss-skip-container&quot;]/button[@class=&quot;ss-skip-action-btn ss-survey-font-family ss-survey-text-size--sm ss-survey-line-height--none ss-survey-text-weight--bold ss-survey-text-color--primary-04&quot;]</value>
      <webElementGuid>24a72124-0e90-4b86-b1b9-0d90235ff726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000139113']/span/div[2]/div/button</value>
      <webElementGuid>40416bc7-2756-448b-b6b8-7034e2e700d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Most Likely'])[1]/following::button[1]</value>
      <webElementGuid>facaaafd-1dea-4387-a758-74d8678261ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neutral'])[1]/following::button[6]</value>
      <webElementGuid>1511aa4e-30f0-46f2-b3fb-99610c6e43cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made with SurveySparrow'])[1]/preceding::button[1]</value>
      <webElementGuid>706f1e46-2156-4430-89c4-af88846279a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made with'])[1]/preceding::button[1]</value>
      <webElementGuid>e22ade1c-5d12-46b6-9965-1b18f05414b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skip']/parent::*</value>
      <webElementGuid>6a2cb287-59e1-4ede-b862-663687e98a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>9b81879d-1937-4f2b-bed3-1243a491c8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>26a11158-9306-41b0-9fe6-61f1239518af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
