<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Report abuse_ss-progress-fill</name>
   <tag></tag>
   <elementGuidId>81a5c98f-da27-4353-a51f-68eab2e4c1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>circle.ss-progress-fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>c44179c1-5640-4f29-9bb1-58ab5f85a3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-progress-fill</value>
      <webElementGuid>8887fa3b-fb8b-4a9d-b27a-94f17478d579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>58c7b897-4473-4d23-b19e-1a12e916c846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4d53061d-2216-4be4-a454-0645cd581ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dasharray</name>
      <type>Main</type>
      <value>138.23007675795088 138.23007675795088</value>
      <webElementGuid>4f84b1b8-d3b3-464c-bd64-6eb96ac7ccd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>14a36258-4a40-4664-a61f-c3d1e9b99443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>540bffc3-e449-4af4-8c88-2f89525339a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c082188b-f970-4ed0-b266-96084c3e7773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[2]/div[@class=&quot;surveysparrow-survey-container--classic-form&quot;]/div[@class=&quot;ss-classic-footer--old&quot;]/div[@class=&quot;ss-classic-footer__left&quot;]/span[@class=&quot;bottom-left ss-progress-container--new ss-survey-text-color--primary ss-survey-font-family ss-survey-text-size--xs ss-survey-line-height--none ss-survey-text-weight--regular&quot;]/svg[1]/circle[@class=&quot;ss-progress-fill&quot;]</value>
      <webElementGuid>36633626-ffbc-45f5-9741-860d7a951851</webElementGuid>
   </webElementProperties>
</WebElementEntity>
