<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0Least Likely12345Neutral678910Most Likely</name>
   <tag></tag>
   <elementGuidId>acfd028e-9fd0-428a-a00e-46bc654414dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question_1000139113']/span/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ss_rating_input--classic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09cdb42e-1528-42f7-bd6d-42d8b24518e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss_rating_input--classic</value>
      <webElementGuid>8c2f0ba2-3d33-4941-8744-1723e3ddf19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radiogroup</value>
      <webElementGuid>e0b56bb8-47a5-4bdd-8872-749f56e22945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>question-title-1000139113</value>
      <webElementGuid>41556d39-5995-419c-902d-67c5eac640f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>question-title-1000139113 question-description-1000139113</value>
      <webElementGuid>4ec47d08-9d54-49e2-adcf-598fd514fb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0Least Likely12345Neutral678910Most Likely</value>
      <webElementGuid>06231fe8-ee51-4eba-afd7-2377c400a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000139113&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_options_container&quot;]/div[@class=&quot;ss_rating_container ss_component_animated&quot;]/div[@class=&quot;ss_rating_input--classic&quot;]</value>
      <webElementGuid>63e9512f-214c-45df-9399-4f470012ee49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000139113']/span/div/div/div</value>
      <webElementGuid>97830a5a-5e81-49ac-bde2-a13070b84a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a opinion question'])[1]/following::div[3]</value>
      <webElementGuid>88c551b7-2879-468f-a002-b5cf8608dfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div</value>
      <webElementGuid>e0e4f836-67fe-4ead-a396-9efdf5b2808b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0Least Likely12345Neutral678910Most Likely' or . = '0Least Likely12345Neutral678910Most Likely')]</value>
      <webElementGuid>89c65a6f-55ce-49b5-82a4-3161a7dd02b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
