<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Question 1</name>
   <tag></tag>
   <elementGuidId>08f29ae1-486e-4c51-9b3e-6b373f43c5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question_1000139113']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.ss-survey-heading--text.ss-survey-font-family.ss-survey-text-size--base.sm_ss-survey-text-size--sm.ss-survey-line-height--normal.ss-survey-text-weight--regular.ss-survey-text-color--primary.ss-survey-text-question-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9d3961e1-a44e-4ffe-9acb-03bcb5989b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-survey-heading--text ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--sm ss-survey-line-height--normal ss-survey-text-weight--regular ss-survey-text-color--primary ss-survey-text-question-text</value>
      <webElementGuid>88a9d599-3c46-4f99-9a48-235968c7713a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Question 1</value>
      <webElementGuid>51435674-22e9-4315-8f53-9a8ba3c14f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000139113&quot;)/div[@class=&quot;ss_cl_survey_qstn_wrapper&quot;]/div[@class=&quot;ss_cl_survey_qstn_left d-flex fx-row fx-ai--center&quot;]/p[@class=&quot;ss-survey-heading--text ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--sm ss-survey-line-height--normal ss-survey-text-weight--regular ss-survey-text-color--primary ss-survey-text-question-text&quot;]</value>
      <webElementGuid>82bd866d-4978-4ba7-a67c-b562104ce06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000139113']/div/div/p</value>
      <webElementGuid>8fca5107-85af-4560-914b-88bf485059fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a opinion question'])[1]/preceding::p[1]</value>
      <webElementGuid>7eca7048-4a29-48cf-bff7-f6028dd0aa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Least Likely'])[1]/preceding::p[3]</value>
      <webElementGuid>7b1bbd3b-4575-45b1-9e7a-a2f8f7b9e188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Question 1']/parent::*</value>
      <webElementGuid>6c1e0063-8222-45eb-8c48-7b401ccbdb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>5cd4a232-df57-4bb5-92db-8d834d02e81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Question 1' or . = 'Question 1')]</value>
      <webElementGuid>89ef472b-4da9-4e2b-bae7-e5f929011598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
