<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_This is a rating question_ss-survey-te_98f8fc</name>
   <tag></tag>
   <elementGuidId>3ad406ac-2165-4367-bca2-e75290aa6a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.ss-survey-text-color--secondary.ss-rating-icon-fill.ss-ratingiconstar-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>5edc7309-075d-4026-b807-9981d27858ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>788de534-583c-4ebe-abb4-390584d9daff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>a9b49b89-e1fa-4aea-943e-58f01fd2b597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>566663e0-cf0f-48f6-a6c8-b219f905123c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>02317f95-782a-49d4-a5d5-5020ef668f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>962e4ddf-02dc-4709-a846-2a3f0b0cd176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-survey-text-color--secondary ss-rating-icon-fill ss-ratingiconstar-3</value>
      <webElementGuid>498c36db-1b36-4854-8cfa-5f2de85c1a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M21.108 2.09a.955.955 0 011.787 0l4.832 13.7h13.646a.955.955 0 01.62 1.68l-11.402 9.454 4.773 14.337a.955.955 0 01-1.47 1.07L22 33.606l-11.9 8.727a.955.955 0 01-1.464-1.071l4.773-14.337L2.004 17.47a.955.955 0 01.62-1.68h13.649l4.835-13.7z</value>
      <webElementGuid>9ef04427-d101-4650-9cd4-ae414b40a2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000139114&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_options_container&quot;]/div[@class=&quot;ss_rating_container ss_rating_container--classic ss_component_animated&quot;]/div[@class=&quot;ss_rating_input&quot;]/button[@class=&quot;answer-option-rating--icons hover-active&quot;]/svg[@class=&quot;ss-survey-text-color--secondary ss-rating-icon-fill ss-ratingiconstar-3&quot;]/path[@class=&quot;ss-survey-text-color--secondary ss-rating-icon-fill ss-ratingiconstar-3&quot;]</value>
      <webElementGuid>5606c704-5bf4-48c3-a497-3105889201a4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
