<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sure, ask</name>
   <tag></tag>
   <elementGuidId>a8e4de56-51f0-4ff0-9db7-f55b3eacffa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div[2]/div/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ss-primary-action-btn__copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>74ac682a-b592-4f1b-a3c9-eb782e7ff77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-primary-action-btn__copy</value>
      <webElementGuid>786571b9-d06f-4260-9236-f2036c35dbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sure, ask.</value>
      <webElementGuid>4bc20fed-31df-4443-a5b7-24c14ca4f67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[2]/div[@class=&quot;surveysparrow-survey-container--classic-form&quot;]/div[@class=&quot;ss-fp-section surveysparrow-survey-form-wrapper--centered ss-survey-background d-flex fx-column fx-jc--center fx-ai--center&quot;]/div[@class=&quot;ss-fp-section__frame ss_classic_survey_intro_contents&quot;]/div[@class=&quot;ss-fp-section__inner-frame&quot;]/div[@class=&quot;ss_cl_qstn_action&quot;]/button[@class=&quot;ss-primary-action-btn ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--base ss-survey-line-height--tight ss-survey-text-weight--bold ss-primary-action-btn--intro&quot;]/span[@class=&quot;ss-primary-action-btn__copy&quot;]</value>
      <webElementGuid>ce060ad0-f583-4303-b724-9a194615be29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div[2]/div/div/div/div/div/button/span</value>
      <webElementGuid>639efd5c-eafc-4566-96fe-1deea51223c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sure, ask.']/parent::*</value>
      <webElementGuid>85e18528-ce88-4e04-a3e6-4e4c81a4ffbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>ee1c1bee-9121-4c06-affd-7b7160aea271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sure, ask.' or . = 'Sure, ask.')]</value>
      <webElementGuid>293625fb-9287-418c-8b2e-af4cf8e9720e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
