<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3Share</name>
   <tag></tag>
   <elementGuidId>6df6d6ed-baf9-4d22-ae68-8a6faa38d17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='share']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06e56d91-1bb7-4279-9545-70b2d481d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-animated--underline</value>
      <webElementGuid>331a6b38-57f6-4058-915d-0352eebcf63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share</value>
      <webElementGuid>b6ac6942-ae64-4520-a74c-19b0f3f9a6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/survey/1000026514/channels</value>
      <webElementGuid>4672fb12-8b29-4f65-a83c-b0147fa96101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3Share</value>
      <webElementGuid>649a747d-5817-4e15-b3b7-2f0ae26473c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share&quot;)</value>
      <webElementGuid>28c42e3e-ff61-48b5-9866-212353b9097f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='share']</value>
      <webElementGuid>7c63f13a-6c8a-4746-ab23-48c0fefbcf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div/div/div[2]/a[3]</value>
      <webElementGuid>d9132b0f-25d8-47e5-aaf2-0058d91d9907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved'])[1]/preceding::a[2]</value>
      <webElementGuid>d0ddefde-cd6a-4e0a-bc5b-c5bbce1b540f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Share']/parent::*</value>
      <webElementGuid>112fb7c3-e858-4396-9e20-086a0508fce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/survey/1000026514/channels')]</value>
      <webElementGuid>14775e67-b6b4-48cd-aad9-1018b39355bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>c71ef482-ad05-4e0c-844c-d320668d55fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'share' and @href = '/survey/1000026514/channels' and (text() = '3Share' or . = '3Share')]</value>
      <webElementGuid>64c47c0c-af8b-41ba-9ea9-d2b300ee8c23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
