<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bulk Choices</name>
   <tag></tag>
   <elementGuidId>d4f5c7af-1c81-4fc6-86a2-d7a480e8a650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings']/div/span/div/div[4]/div[2]/div/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70d598df-ebb5-4986-bbbc-a070a559d568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>fcad7dfc-2bdf-48f0-8a9d-9116b42fcac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk Choices</value>
      <webElementGuid>45e77ac6-4aa0-4840-8963-c1ebc114bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings&quot;)/div[@class=&quot;c_builder_contents&quot;]/span[@class=&quot;ss_builder_container&quot;]/div[@class=&quot;ss_content_wrapper&quot;]/div[@class=&quot;ss_row--builder&quot;]/div[@class=&quot;ss_question_settings_container&quot;]/div[@class=&quot;c-br-actions&quot;]/div[@class=&quot;ss_builder_container_boxed_title_bg flex-wrap box--bordered&quot;]/div[@class=&quot;c-br-actions-left&quot;]/div[@class=&quot;bordered_btn_right&quot;]/a[@class=&quot;btn&quot;]</value>
      <webElementGuid>fd9c036d-d579-4f25-a4db-57521f3286b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings']/div/span/div/div[4]/div[2]/div/div/div/div[4]/a</value>
      <webElementGuid>c7c511ef-ebd1-4fe9-9abe-110e4efe7623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bulk Choices')]</value>
      <webElementGuid>2987e0b5-cfb4-4150-ac42-bcde37352388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logic'])[1]/following::a[1]</value>
      <webElementGuid>6ba39c32-9e97-4703-bee6-9fbac7b34f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::a[2]</value>
      <webElementGuid>1b10ce76-7bcf-434c-b2d3-802b384d4e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Score'])[1]/preceding::a[1]</value>
      <webElementGuid>9c84a016-e595-423e-b6e7-a38aa8b02861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::a[1]</value>
      <webElementGuid>5aeb4de9-1735-4589-afbd-09219938b4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulk Choices']/parent::*</value>
      <webElementGuid>d3288c17-186a-4e67-b3fa-d8254036c8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>8bb0230d-5385-46a2-9203-bf2e2278037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Bulk Choices' or . = 'Bulk Choices')]</value>
      <webElementGuid>29101565-991e-4ca5-9026-123a7a29a0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
