<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Survey</name>
   <tag></tag>
   <elementGuidId>efa038fa-9ad4-4de9-a069-520ec3ab7c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tracking-navbar__create-new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tracking-navbar__create-new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29fc0aba-6e34-44fa-95c4-2ad0bce11880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button ss-button__primary mx-0 create-new-btn</value>
      <webElementGuid>1761a380-98ae-4749-9919-ec85e825cbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d51128c9-1315-470c-a503-540730695d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tracking-navbar__create-new</value>
      <webElementGuid>f5681d74-96b6-4b01-b619-df3b45c9ee9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Survey</value>
      <webElementGuid>1a989b7a-3915-40f2-8715-491040e92411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tracking-navbar__create-new&quot;)</value>
      <webElementGuid>018845be-e138-4980-bda3-ead2a1cf1804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tracking-navbar__create-new']</value>
      <webElementGuid>f33abeb2-7f89-4551-8e69-777873d69607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div[2]/div[3]/a</value>
      <webElementGuid>2ddf05e4-88f6-4ac2-af1d-27b9b63d67ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Survey')]</value>
      <webElementGuid>e9727ac6-2a18-404f-8000-0f51fa50e7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed'])[1]/following::a[1]</value>
      <webElementGuid>42497f3e-7246-44e3-aedd-5605413bbd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      <webElementGuid>19707a20-519c-4c17-a6ec-b1f7f5bbfc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_katalon_demo_spf'])[1]/preceding::a[1]</value>
      <webElementGuid>98b4f55e-9d27-4863-9e71-4e367b44579d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Survey']/parent::*</value>
      <webElementGuid>52c7c615-c469-4edf-8613-98be3d9e09d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>a269178e-f689-455c-86fc-220a4d9939a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tracking-navbar__create-new' and (text() = 'New Survey' or . = 'New Survey')]</value>
      <webElementGuid>556045c1-ecf8-4aa3-9c93-55d418120110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
