<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start typing_public-DraftStyleDefault-b_9cab06</name>
   <tag></tag>
   <elementGuidId>bb8b94ef-7219-4f4a-8665-8e846062a53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qcontainer']/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.public-DraftStyleDefault-block.public-DraftStyleDefault-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c778d41f-eb25-4259-b1a6-719c4c5c3239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-key</name>
      <type>Main</type>
      <value>1hern-0-0</value>
      <webElementGuid>ea9658ee-d31d-47e9-8187-dc5dbd58810e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>public-DraftStyleDefault-block public-DraftStyleDefault-ltr</value>
      <webElementGuid>afb91614-fb9d-4b5a-bd9e-49d4b0a88571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings&quot;)/div[@class=&quot;c_builder_contents&quot;]/span[@class=&quot;ss_builder_container&quot;]/div[@class=&quot;ss_content_wrapper&quot;]/div[@class=&quot;ss_row--builder&quot;]/div[@class=&quot;ss_chat ss_bot active ss-question-wrapper&quot;]/div[@class=&quot;ss-question-text&quot;]/div[@id=&quot;qcontainer&quot;]/div[1]/div[@class=&quot;DraftEditor-root&quot;]/div[@class=&quot;DraftEditor-editorContainer&quot;]/div[@class=&quot;notranslate public-DraftEditor-content&quot;]/div[1]/div[1]/div[@class=&quot;public-DraftStyleDefault-block public-DraftStyleDefault-ltr&quot;]</value>
      <webElementGuid>57287413-ffea-44d0-961f-38a0a830976b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qcontainer']/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>1d47788c-b886-4d6d-887c-8b755bc76f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start typing...'])[1]/following::div[5]</value>
      <webElementGuid>c748f020-d8b7-47fb-bd13-7d58bd50799d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::div[16]</value>
      <webElementGuid>76593e0a-7f77-409b-951a-013ece3f3bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add description to your question.'])[1]/preceding::div[8]</value>
      <webElementGuid>ebf47ca2-8b42-4b27-b093-f24c829a1cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/preceding::div[40]</value>
      <webElementGuid>d8f49ee1-2116-4582-9a12-f90646d33ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>33030f05-0946-40e7-a02c-29b253e73b3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
