<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Profile_ss-icon-delete_forever</name>
   <tag></tag>
   <elementGuidId>452fa738-fde1-464d-b05f-bc05d0d8f25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c0e895b2-0425-4ba1-8b66-d7ca5c09985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-icon-delete_forever  </value>
      <webElementGuid>1005c2d4-6902-4682-b590-e650c1acbcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1af0634-b40a-4abc-9e53-85f6bcfbf6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--classic fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-builder--wrapper fx-row fx-ai--stretch&quot;]/div[@class=&quot;left_sidebar sidebar_builder border-right&quot;]/div[@class=&quot;left_sidebar_content c_gp1&quot;]/div[@class=&quot;left_sidebar_section&quot;]/div[@class=&quot;ss-sections-wrapper&quot;]/div[@class=&quot;ss-section-container ss-section-container--brown&quot;]/div[@class=&quot;ss-section-actionbar border-radius--xl&quot;]/div[@class=&quot;ss-section-actions border-radius--xl&quot;]/a[@class=&quot;btn&quot;]/i[@class=&quot;ss-icon-delete_forever&quot;]</value>
      <webElementGuid>e1babeb4-bd04-4eca-bef7-2c12310e8a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/a/i</value>
      <webElementGuid>87af4cf2-f245-4d1e-a35e-ec12272d06f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>4bdf28ac-760e-423a-b1c4-24737d92b7b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
