<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Logic_checkmeout-checkbox-style</name>
   <tag></tag>
   <elementGuidId>4e25be66-e0e9-41ba-85f5-b3df09ed3694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings']/div/span/div/div[2]/div/div/div[2]/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.checkmeout-checkbox-style</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9dd25c69-37ec-45c6-9c7d-e1309ec6b187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmeout-checkbox-style</value>
      <webElementGuid>7186c242-2d3d-4881-a9fc-d28b9e5b2483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>singlePageView</value>
      <webElementGuid>1c433aaf-fb86-46ae-827b-2b817818e05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings&quot;)/div[@class=&quot;c_builder_contents&quot;]/span[@class=&quot;ss_builder_container&quot;]/div[@class=&quot;ss_content_wrapper ss_content_wrapper--sections&quot;]/div[@class=&quot;ss_question_settings_container&quot;]/div[@class=&quot;c-br-actions&quot;]/div[@class=&quot;ss_builder_container_boxed_title_bg box--bordered&quot;]/div[@class=&quot;c-br-actions-right&quot;]/div[@class=&quot;fx-row&quot;]/div[@class=&quot;fx-row&quot;]/div[@class=&quot;checkmeout-checkbox checkmeout-checkbox-sm mr--sm me-3&quot;]/label[@class=&quot;checkmeout-checkbox-style&quot;]</value>
      <webElementGuid>8f79de5a-1e83-482d-b911-928062693e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings']/div/span/div/div[2]/div/div/div[2]/div/div/div/label</value>
      <webElementGuid>84fc4444-9762-47f0-8ed2-fc4aae04da39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a3656afd-fbc7-4f51-ae2c-5485eb1e7cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
