<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Display Section Intro_checkmeout-switch-style</name>
   <tag></tag>
   <elementGuidId>d12864bf-117a-4338-b9bf-1751ff29b6f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings']/div/span/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.checkmeout-switch-style</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ad5aea80-0dea-4519-a6ac-634d5e9431b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmeout-switch-style</value>
      <webElementGuid>4f5f14dc-db14-448f-b9fd-d9b1b268af78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings&quot;)/div[@class=&quot;c_builder_contents&quot;]/span[@class=&quot;ss_builder_container&quot;]/div[@class=&quot;ss_content_wrapper ss_content_wrapper--sections&quot;]/div[@class=&quot;ss_question_settings_container&quot;]/div[@class=&quot;c-br-actions&quot;]/div[@class=&quot;ss_builder_container_boxed_contents&quot;]/div[@class=&quot;c-br-actions-row&quot;]/div[@class=&quot;action-block-container&quot;]/div[@class=&quot;flex-row generic-action-container&quot;]/div[@class=&quot;flex-column&quot;]/div[@class=&quot;fx-row mt--xs&quot;]/div[@class=&quot;fx-row&quot;]/label[@class=&quot;checkmeout-switch mr--sm&quot;]/span[@class=&quot;checkmeout-switch-style&quot;]</value>
      <webElementGuid>79034d32-83b6-4d3a-99ac-b488ca5ae479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings']/div/span/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/label/span</value>
      <webElementGuid>b5709d8d-88ee-407b-b7d1-7758f1b6a931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>56eb68bc-aeb9-4f8b-ad94-2777cb40b676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
