<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3Share</name>
   <tag></tag>
   <elementGuidId>cac50f48-f987-471d-8db4-9711bdf59c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='share']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35ef4d15-447c-426a-a0b5-c4fcbd1dce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-animated--underline</value>
      <webElementGuid>3187d528-a34e-4861-a995-b010abd356e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share</value>
      <webElementGuid>b5e531c7-eebb-4f04-a1f7-defb9cfd1d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/survey/1000020928/channels</value>
      <webElementGuid>c28b6b7a-8586-4093-a2b8-3dd9a43bc8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3Share</value>
      <webElementGuid>f30b0bc4-30ba-43fb-98be-2e8d7985ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share&quot;)</value>
      <webElementGuid>886c983d-2629-4b79-ac69-8b186e76ced6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='share']</value>
      <webElementGuid>6d377238-a43c-40fb-8b5c-580b6d2d3050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>2a9c162a-95a6-423c-b63b-841b744a1933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved'])[1]/preceding::a[2]</value>
      <webElementGuid>196c0a2e-4e6d-414a-9b7f-b1d8467d0e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Share']/parent::*</value>
      <webElementGuid>144e7d27-7fb6-40fc-baba-2a9e513347be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/survey/1000020928/channels')]</value>
      <webElementGuid>f00ba9ec-cb47-4cd8-b12e-82384b34c630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>df892a41-aa51-45cd-98c5-a49af9d51aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'share' and @href = '/survey/1000020928/channels' and (text() = '3Share' or . = '3Share')]</value>
      <webElementGuid>3a77554d-b079-4a93-b778-17a4d456a137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
