<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4Results</name>
   <tag></tag>
   <elementGuidId>1fa27e25-6e89-4bb2-8fe8-ac3c7e473a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d910cbd1-8a65-4737-94c8-7850a8efb4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-animated--underline</value>
      <webElementGuid>31ba44d4-eff8-4778-b924-d749877620d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>results</value>
      <webElementGuid>b5aedb7c-ac77-4f7c-9f80-5acff9be86d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/survey/1000020928/results/overview</value>
      <webElementGuid>97d12169-4ec2-4266-95dd-17783d0e7ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4Results</value>
      <webElementGuid>a0fbb51a-687c-43fb-8047-42f892421ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results&quot;)</value>
      <webElementGuid>f9597a2a-7718-4512-82fb-fb12bc8a7b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='results']</value>
      <webElementGuid>744ea526-5d84-4758-974f-861a85b206a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div/div[2]/a[4]</value>
      <webElementGuid>54d14f9a-a471-40c9-bb66-6468044a6084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::a[1]</value>
      <webElementGuid>12556cd4-52f6-4cb7-90ee-d1b45ee290f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Survey'])[1]/preceding::a[1]</value>
      <webElementGuid>35d7100e-624d-4410-9515-64e1ac7133f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::a[1]</value>
      <webElementGuid>b2b0a2ca-4524-4547-a500-188031a58266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Results']/parent::*</value>
      <webElementGuid>6028f223-5e4d-4e0c-8f0b-942b213ee640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/survey/1000020928/results/overview')]</value>
      <webElementGuid>14b9fa74-0064-4e01-aef8-a2219b1c1f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>a7698791-f405-46fa-8797-1a9a66000cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'results' and @href = '/survey/1000020928/results/overview' and (text() = '4Results' or . = '4Results')]</value>
      <webElementGuid>b0991f1e-2ec1-41e2-8b94-bbb31a3964b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
