<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contacts_1</name>
   <tag></tag>
   <elementGuidId>d6a23e04-3e12-4bd2-bf94-80bd475b469f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ss-drop-menu-32']/li/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.flex-column.ms-1.ss-text__color--black > a.ss-button.ss-button__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a32f2dc-657e-4ced-8521-728564ff9bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button ss-button__text</value>
      <webElementGuid>447d9048-b758-4487-a0a2-9adafc09d309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/audience</value>
      <webElementGuid>b682f8c3-0d8d-42ae-b5ce-e93f1937d545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacts</value>
      <webElementGuid>295d7842-b677-47c7-b74a-e235404f2896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper ss-main-wrapper--fixed-scrolling&quot;]/div[@class=&quot;ss-dashboard--navbar grid grid-nogutter fx-row fx--fw wplr--md px-5 px-md-6 border-bottom bg-grey-7 justify-content-between&quot;]/div[@class=&quot;ss-dashboard--navbar-left col-3 col-lg-6 fx-row&quot;]/div[@class=&quot;ss-dashboard--navbar-item fx-row fx-ai--center px-3 px-xl-4 contacts-dropdown position--relative ss-animated--underline&quot;]/div[@class=&quot;ss-button--dropdown ss-button--dropdown--open ss-text__size--h3&quot;]/ul[@id=&quot;ss-drop-menu-32&quot;]/li[@class=&quot;d-flex justify-content-between py-3 align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;d-flex flex-column ms-1 ss-text__color--black&quot;]/a[@class=&quot;ss-button ss-button__text&quot;]</value>
      <webElementGuid>391e9b84-419f-4609-841d-8c0deae953a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ss-drop-menu-32']/li/div/div/a</value>
      <webElementGuid>25392192-68a7-4353-bce6-fbdd0370be94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contacts')])[2]</value>
      <webElementGuid>06f10fb7-b71c-48a0-90ef-c2787f94afc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::a[1]</value>
      <webElementGuid>41bae110-9bd1-4b06-a213-fd59f37f3669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[1]/following::a[2]</value>
      <webElementGuid>30e622b9-2d50-441e-9f3d-4d01d21fcb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employees'])[1]/preceding::a[1]</value>
      <webElementGuid>c5fa43cf-0e20-4141-933b-b9093bdbb662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reputation'])[1]/preceding::a[2]</value>
      <webElementGuid>0d7ae61a-7f57-46e2-ba11-249da78d917b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/audience')]</value>
      <webElementGuid>91440011-0648-473e-b27b-43b5de9c4494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/a</value>
      <webElementGuid>6e433fdc-ae77-49e9-85ee-fc022815e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/audience' and (text() = 'Contacts' or . = 'Contacts')]</value>
      <webElementGuid>a53085db-c92c-482a-98a2-abdf7588a0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
