<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NextSave Schedule</name>
   <tag></tag>
   <elementGuidId>6207e979-72f2-4a35-9d1c-504a88b1c954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ss-button.ss-button__primary.ss-text__transform--uppercase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a554444b-5b38-4895-b528-3f5d6d4214f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button ss-button__primary ss-text__transform--uppercase</value>
      <webElementGuid>3956cafc-3dda-4483-8d4c-050fc65f816d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>977be914-cfa5-43a6-abc6-c292ca0d503c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NextSave Schedule</value>
      <webElementGuid>24b420b4-355e-41bb-ac64-66175ae43ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--csat-chat fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-share--footer fx-row fx-jc--between&quot;]/a[@class=&quot;ss-button ss-button__primary ss-text__transform--uppercase&quot;]</value>
      <webElementGuid>bdbccbd5-fd2c-468c-96c1-8e36edd1cfb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div[2]/a[2]</value>
      <webElementGuid>97c7b8e4-3c6c-4b67-9bd5-e8479f5ae307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Design Page'])[1]/following::a[1]</value>
      <webElementGuid>918d9430-1d94-4eaf-9d47-3b25323d54be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/following::a[2]</value>
      <webElementGuid>bbe5c124-7620-4e0f-8a37-3290884f6ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Schedule']/parent::*</value>
      <webElementGuid>68901381-bdce-4594-805b-e022a428bbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a[2]</value>
      <webElementGuid>72b63ca6-9364-4a65-851e-9543c22c58e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'NextSave Schedule' or . = 'NextSave Schedule')]</value>
      <webElementGuid>7d0c9d4e-0805-42dd-a69f-0b3b7017b4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
