<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Survey</name>
   <tag></tag>
   <elementGuidId>bf99801b-c355-44e9-9839-3d204e778858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tracking-navbar__create-new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tracking-navbar__create-new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c1bc9f6-545b-46f6-8d27-0fd4202c63ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button ss-button__primary mx-0 create-new-btn</value>
      <webElementGuid>a6c81101-68b9-4744-96ab-4c77148b6a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14abf990-3cd6-429d-935d-29d37378f977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tracking-navbar__create-new</value>
      <webElementGuid>05b3da6a-6941-4bad-8e0a-025ce45bc8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Survey</value>
      <webElementGuid>df664b63-efb3-46df-84bd-bc4ca72a7307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tracking-navbar__create-new&quot;)</value>
      <webElementGuid>416560c6-ee06-41ca-9eeb-083b42d9e81f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tracking-navbar__create-new']</value>
      <webElementGuid>af7dbce3-4fce-427e-a19a-2d9e1aeb2c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div[2]/div[3]/a</value>
      <webElementGuid>05fe0b10-6847-4d31-b8be-6c880c8c7790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Survey')]</value>
      <webElementGuid>d40402a1-2bda-4f30-a2bc-11f1e3e02dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed'])[1]/following::a[1]</value>
      <webElementGuid>e84cdf68-2cc3-4fdd-8ccc-6f90a274df1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::a[1]</value>
      <webElementGuid>870e4c5e-db05-4a2a-8051-81ee4d2f6d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='update'])[1]/preceding::a[1]</value>
      <webElementGuid>1f84c3ae-dc96-4945-81e4-71e3b0ecefc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Survey']/parent::*</value>
      <webElementGuid>2b286630-c106-4db9-8193-e571072dd878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>24e49ca3-07ab-4942-8636-ae6e792a6833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tracking-navbar__create-new' and (text() = 'New Survey' or . = 'New Survey')]</value>
      <webElementGuid>1c29e4a3-8d4c-4939-8a7d-c15887e6bea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
