<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Share</name>
   <tag></tag>
   <elementGuidId>aada57f1-ebbc-4206-9478-29f3b0a4ff8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='share']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78abffb6-1f82-402d-9f06-578cfaa9922c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-animated--underline</value>
      <webElementGuid>02c37958-d215-4e04-bd17-e09df992b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share</value>
      <webElementGuid>099ce6d5-3427-45a7-a024-8b26f5ca381f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/survey/1000012375/channels</value>
      <webElementGuid>709020b2-867b-4d15-bd39-cf64d145e68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share</value>
      <webElementGuid>e45425d0-2a79-4a89-8ea7-8859f4f727d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share&quot;)</value>
      <webElementGuid>f486eead-8d08-4829-8685-416bff655c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='share']</value>
      <webElementGuid>ec678ab0-c771-453d-9dc5-3c9678453356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div/div[2]/a[3]</value>
      <webElementGuid>4cdea57e-9caa-4525-8a2f-3ca6b8d826ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Share')]</value>
      <webElementGuid>accce442-0ed4-4055-ba8f-1ff479599e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Survey'])[1]/preceding::a[2]</value>
      <webElementGuid>1a25d4a1-3f31-46a1-95cb-cc36e7c61f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Share']/parent::*</value>
      <webElementGuid>cfb8a5e6-2424-4227-a2e3-353ced01e5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/survey/1000012375/channels')]</value>
      <webElementGuid>7083bd41-0a73-4c01-86dc-4d220ee34116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>3e943b63-d1b7-4277-ad00-2b9be1e949e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'share' and @href = '/survey/1000012375/channels' and (text() = 'Share' or . = 'Share')]</value>
      <webElementGuid>f83e1ce4-4f43-4d4f-889d-2ac4aa54bc06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
