<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Opinion Scale</name>
   <tag></tag>
   <elementGuidId>dc507dc6-deb3-4a63-93c7-9b10d495b7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OSQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OSQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25dc5e99-4fd5-45b4-af1e-9994db5a1085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OSQ</value>
      <webElementGuid>64bbec6d-bc9d-4053-8042-728c2c955f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-question-item</value>
      <webElementGuid>4f4dffd0-2e47-421c-8a05-09e240d8c8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa35ec08-88a3-4274-b8f4-a49027093ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Opinion Scale</value>
      <webElementGuid>8aefd8ce-c590-473a-a2c0-ef92e81a8878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OSQ&quot;)</value>
      <webElementGuid>152334f9-9087-46b4-a394-dec18a167d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='OSQ']</value>
      <webElementGuid>b405d2db-23e7-45e5-8985-0b703e979368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/span/div</value>
      <webElementGuid>be0f8868-ed1f-4216-85a6-0d76b4644988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Used'])[1]/following::div[3]</value>
      <webElementGuid>1788ebb0-f40c-422a-896f-3ab4c03871e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Page'])[1]/following::div[3]</value>
      <webElementGuid>d326aec1-f32f-4be0-b1cf-ccc851b6d077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiple Choice'])[1]/preceding::div[1]</value>
      <webElementGuid>9bc9cecf-df7c-4b3c-b73f-42aef1cd0ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/div</value>
      <webElementGuid>a705f35d-47a7-4537-a326-0e06b4dd30d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'OSQ' and (text() = 'Opinion Scale' or . = 'Opinion Scale')]</value>
      <webElementGuid>c48cab7d-14e2-4565-bde1-a2600d008942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
