<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Section</name>
   <tag></tag>
   <elementGuidId>60cc6cb4-7400-43ed-bfe1-59cc7d0fbbf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SEC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76660586-15a4-4ec1-b55b-f9e5327545a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SEC</value>
      <webElementGuid>b366c313-99d4-46b3-ba2f-0fe7524f6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-question-item</value>
      <webElementGuid>d3e5d6a0-be92-48e4-b4bd-4c093a10047b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e4b001be-79d7-4039-a834-c5ad35550f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Section</value>
      <webElementGuid>c280b583-ee2a-470b-be67-95deebc771a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SEC&quot;)</value>
      <webElementGuid>0860c63d-e062-4341-bda2-c58bcf61e862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SEC']</value>
      <webElementGuid>9f0b3b01-7179-4763-b3a0-3339ca634890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/div[3]/div/span/div</value>
      <webElementGuid>fc5e7904-9027-4d37-be88-4e4ed1113591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[1]/following::div[3]</value>
      <webElementGuid>f21c552d-e398-4abc-8521-926bc79ff512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::div[3]</value>
      <webElementGuid>fdd823ea-695f-4f89-b001-462b8b9b6a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picture Choice'])[1]/preceding::div[1]</value>
      <webElementGuid>88e0cfe4-cb14-408a-bbc3-f64097fa6006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div</value>
      <webElementGuid>dd003866-f130-44a0-9292-a3779b13cb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SEC' and (text() = 'Section' or . = 'Section')]</value>
      <webElementGuid>06e828ec-736e-4997-b3c7-5244537cfac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
