<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create SurveyContactsBillingSettingsHel_d36398</name>
   <tag></tag>
   <elementGuidId>e4a8ee60-f97c-48f2-a80c-6dd1c9eb6fe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ss-button--dropdown.ss-header--wrapper__drop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[2]/div/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>624ad1cb-bec4-4288-8456-fc17a74dd7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>267d9a31-978b-4652-ab95-ba489be66bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button--dropdown ss-header--wrapper__drop</value>
      <webElementGuid>09b235aa-0cdf-429a-a35f-e31888726c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37c41e9e-fe97-47cb-b8ea-e71312ea181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7d086d8-05fb-46e4-aef4-8b56763765dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ss-drop-menu-4</value>
      <webElementGuid>68cdc25c-582d-43be-aa9b-52a04c6792c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menubar</value>
      <webElementGuid>9db33257-6a36-4d8d-9955-dc0851261632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create SurveyContactsBillingSettingsHelpProfile</value>
      <webElementGuid>4775c0df-de6a-48e7-80e0-56c9ab9ad3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;ss-header--wrapper&quot;]/div[@class=&quot;ss-header ss-header--classic&quot;]/div[@class=&quot;col-3 fx-row fx-jc--end ss-float--right&quot;]/div[@class=&quot;ml--lg&quot;]/div[@class=&quot;fx-row&quot;]/div[@class=&quot;ss-button--dropdown ss-header--wrapper__drop&quot;]</value>
      <webElementGuid>ed4a5803-8a75-4027-a9f3-864fa15907b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div/div[3]/div/div/div</value>
      <webElementGuid>ccc61276-10c0-408f-b969-91cfc376087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::div[4]</value>
      <webElementGuid>73377fea-28ad-441e-9fa0-5fc1f117d1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div</value>
      <webElementGuid>596278b4-5ac3-4fe2-889e-31fb026a6089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create SurveyContactsBillingSettingsHelpProfile' or . = 'Create SurveyContactsBillingSettingsHelpProfile')]</value>
      <webElementGuid>e7b06d7d-d9a4-41be-a284-7c6760f60f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
