<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_46</name>
   <tag></tag>
   <elementGuidId>97c1a7eb-3f2a-4733-a357-9b45b00bb2d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1szy77t-control.ss-react-select__control.ss-react-select__control--is-focused.ss-react-select__control--menu-is-open > div.css-1hwfws3.ss-react-select__value-container.ss-react-select__value-container--has-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div/div/div/div[3]/div/div[2]/div[5]/div[3]/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>532318b6-c5c9-409a-9b26-ff9d512dc705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1hwfws3 ss-react-select__value-container ss-react-select__value-container--has-value</value>
      <webElementGuid>369df96c-8818-4024-8733-6315c37e4dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>ef8f06ec-3cae-49fa-b241-a463b0a7e2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--csat-chat fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-share--wrapper fx-row fx-jc--center&quot;]/div[@class=&quot;ss-share--container fx-row fx-ai--stretch fx-as--center mt--auto mb--auto&quot;]/div[@class=&quot;ss-share-form--wrapper&quot;]/div[@class=&quot;ss-nps-share-sms-form--wrapper fx-column&quot;]/div[@class=&quot;grid grid-nogutter ss-animate--fadeIn&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;ss-nps-schedule-from--wrapper&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;flex_column ss-form--input-group ss-form--input-group__no-padding&quot;]/div[@class=&quot;css-1pcexqc-container ss-react-select-container&quot;]/div[@class=&quot;css-1szy77t-control ss-react-select__control ss-react-select__control--is-focused ss-react-select__control--menu-is-open&quot;]/div[@class=&quot;css-1hwfws3 ss-react-select__value-container ss-react-select__value-container--has-value&quot;]</value>
      <webElementGuid>b79ca2e2-db4f-4d2a-95cf-c7c681313185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div/div/div/div[3]/div/div[2]/div[5]/div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>1c74543a-1dee-4f13-a122-a193950e7758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/following::div[24]</value>
      <webElementGuid>9476325d-b94c-47ae-a300-78ca7bd9ad39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEEKLY'])[1]/following::div[36]</value>
      <webElementGuid>145053c8-9b4e-481a-aee2-7aedb1f922e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM'])[1]/preceding::div[69]</value>
      <webElementGuid>826d416a-224f-4e25-a065-2f203ad5f19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SET REMINDER TO NON RESPONDENTS'])[1]/preceding::div[80]</value>
      <webElementGuid>9d736ce9-4af7-4fd1-8a5b-204b6950d204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>17ce3750-7d4a-4624-b831-dd8a22d17848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '46' or . = '46')]</value>
      <webElementGuid>217a56d2-f4fa-487b-8242-c88b02a6c243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
