<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Multiple Choice</name>
   <tag></tag>
   <elementGuidId>a963be92-5052-49ff-974a-438d9f3cbbda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MCQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MCQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9de58d06-174a-452a-9f5e-d4981f2fcbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MCQ</value>
      <webElementGuid>1dea9849-4f7a-4233-ba6f-be8346b24211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-question-item</value>
      <webElementGuid>b881c008-31d1-4dc5-bbd5-e1bc36df3038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7bfd2b84-ca85-4082-a9f3-3b1489ae4b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multiple Choice</value>
      <webElementGuid>76f1e1e0-dd79-4b85-a5d9-932d6d757ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MCQ&quot;)</value>
      <webElementGuid>c452a89b-5ef8-4142-977b-9ece1859e61c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='MCQ']</value>
      <webElementGuid>3af59401-2bd6-4ce5-a8d7-e1e483c1fa10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div[2]/span/div</value>
      <webElementGuid>5c65cf5b-a2c3-4371-96bb-5c83148a9928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opinion Scale'])[1]/following::div[2]</value>
      <webElementGuid>d1bdf38a-cd98-4b05-be2f-e9e772205f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Used'])[1]/following::div[5]</value>
      <webElementGuid>9764f80a-ed9b-4004-b4cf-9d90084065f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[1]/preceding::div[1]</value>
      <webElementGuid>cf8d860f-e064-447e-abe8-9fe7b86e215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div</value>
      <webElementGuid>c685f679-6fb7-491b-a638-5fa738e23ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'MCQ' and (text() = 'Multiple Choice' or . = 'Multiple Choice')]</value>
      <webElementGuid>fe864904-2cc2-4436-ba85-ce03d3053fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
