<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TEProfile SettingsSwitch to PortalRefer_41a6fe</name>
   <tag></tag>
   <elementGuidId>de670845-0ec2-417e-8de8-e028af6b1474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[2]/div[2]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99029e10-ac1c-41ae-9f4a-ed51bc13ab1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ddc5b47-fc5d-4b5e-98bc-bd7ae4598225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button--dropdown</value>
      <webElementGuid>0b1f9938-d188-45aa-904f-05440d73a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff9afd8f-901e-4573-993d-2842ce7fd38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd0730ec-df9d-4be9-8ee7-2298d60884b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ss-drop-menu-16</value>
      <webElementGuid>94e904de-f43e-441a-931a-0b95a094ab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menubar</value>
      <webElementGuid>c62e4826-3f08-40c5-b31b-e58f1b9207bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEProfile SettingsSwitch to PortalReferralsLogout</value>
      <webElementGuid>98a82c3e-f7ed-450a-b614-ad4edb1f86d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper ss-main-wrapper--fixed-scrolling&quot;]/div[@class=&quot;ss-dashboard--navbar grid grid-nogutter fx-row fx--fw wplr--md px-5 px-md-6 border-bottom bg-grey-7 justify-content-between&quot;]/div[@class=&quot;fx-row fx-jc--end&quot;]/div[@class=&quot;fx-row&quot;]/div[@class=&quot;ss-button--dropdown&quot;]</value>
      <webElementGuid>0bc29fb0-3a58-4ac1-8b09-8d3c30a4d17a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div[2]/div[4]/div</value>
      <webElementGuid>c0efd1c0-6005-442e-a9e0-667f1c66caf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[2]/following::div[2]</value>
      <webElementGuid>381be15e-65ad-4784-b768-ee63bc70a415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's New?')])[1]/following::div[2]</value>
      <webElementGuid>3158b7ce-e689-40c5-b6bd-cbcddd1c461e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>22b1dba7-2793-4d4a-8a6d-95f5e011c66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TEProfile SettingsSwitch to PortalReferralsLogout' or . = 'TEProfile SettingsSwitch to PortalReferralsLogout')]</value>
      <webElementGuid>b383f399-4849-488a-885e-2aa7bd74d69d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
