<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EditDelete</name>
   <tag></tag>
   <elementGuidId>f5acc7a8-4455-4f12-ab33-cd5c88c6586e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ss-share-distribution__channel-more-options > div.ss-button--dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54654186-ed45-4588-a98c-103b88144195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6ea58be-85ee-4621-bab9-3031173a3f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-button--dropdown</value>
      <webElementGuid>ec4bcd27-3e34-4179-903c-4d7becc18a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d257528-1922-462a-9038-61a747e57e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>78177874-fa3f-41f3-906d-aad0376e4d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ss-drop-menu-90</value>
      <webElementGuid>260e0328-38c7-4c0c-b789-92bdf2d1d656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menubar</value>
      <webElementGuid>ec938e8d-9cc5-4450-86d5-cbda376759ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditDelete</value>
      <webElementGuid>016221d7-e5e4-4ffd-b68d-30acea754fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--csat-chat fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-dashboard--wrapper d-flex w-100&quot;]/div[@class=&quot;fx-grow-1 h-100&quot;]/div[@class=&quot;ss-container--scrollable ss-nps-active-share-table ss-share-distribution&quot;]/div[@class=&quot;grid h-100&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;grid grid-nogutter ss-animate--fadeIn mt--xl&quot;]/div[@class=&quot;col-12&quot;]/div[1]/div[@class=&quot;ss-share-distribution__item  d-flex flex-column mb-4 shadow-1&quot;]/div[@class=&quot;row py-3&quot;]/div[@class=&quot;col-5&quot;]/div[@class=&quot;d-flex w-100 h-100 align-items-center justify-content-between&quot;]/div[@class=&quot;ss-share-distribution__item--controls d-flex align-items-center pe-3&quot;]/div[@class=&quot;ss-share-distribution__channel-more-options&quot;]/div[@class=&quot;ss-button--dropdown&quot;]</value>
      <webElementGuid>c005b76a-5063-4893-a566-7645e2ad4aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>aa2d623b-4e84-427a-af2a-cf43cc2aa211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next: 10 July 2023 04:48 AM'])[1]/following::div[7]</value>
      <webElementGuid>a825ae62-6b28-4ef9-b053-210aee3b49a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS Share 1'])[1]/following::div[11]</value>
      <webElementGuid>12f71b1e-d940-4801-b754-2385c35174b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div</value>
      <webElementGuid>cec4ccfe-c276-478e-8461-d2614dcd0afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EditDelete' or . = 'EditDelete')]</value>
      <webElementGuid>9bb0516c-dc16-44cd-967c-a2d1480211cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
