<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Automated CSAT Chat Survey Created on 20</name>
   <tag></tag>
   <elementGuidId>dda27c2b-74c6-4102-a0ab-d42f548cd1d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div[2]/div/div/div[4]/div/div/div[3]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>c63f3867-eb62-4618-9574-a0b7af95198b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-text ss-text__size--h3 ss-text__weight--semibold ss-text__color--black mb--xs ss-text__overflow-wrap</value>
      <webElementGuid>f3df0303-793a-4322-9fe4-58927f70a8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spiketip-title</name>
      <type>Main</type>
      <value>Automated CSAT Chat Survey Created on 2023-07-03 11:53:57.453293</value>
      <webElementGuid>1c6d3b4d-6d62-4ce2-8b47-76ea7c4da5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spiketip-length</name>
      <type>Main</type>
      <value>lg</value>
      <webElementGuid>4d042135-62b0-4b08-bdea-67da1dabdd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spiketip-pos</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>6a16f514-36d1-432a-823c-12f3b8994942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automated CSAT Chat Survey Created on 20...</value>
      <webElementGuid>cd040105-0ca6-4d52-8f94-8706fa4c8b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper ss-main-wrapper--fixed-scrolling&quot;]/div[@class=&quot;ss-dashboard--wrapper fx-row fx-ai--stretch bg-grey-7&quot;]/div[@class=&quot;ss-dashboard--container fx--fh fx-grow-1 fx-column pt-5 pt-xl-6&quot;]/div[@class=&quot;ss-dashboard-home--wrapper&quot;]/div[@class=&quot;ss-dashboard--contents px-5 px-xl-11 pb-7&quot;]/div[@class=&quot;ss-dashboard--inner-container px-5 px-xl-6 py-5 py-xl-7 h-100 bg-white&quot;]/div[@class=&quot;ss-dashboard__survey-list-container ss-scrollbar--hide ss-animate--fadeIn&quot;]/div[@class=&quot;row no-gutters w-100 py-5 px-xl-3 ss-dashboard__list-item justify-content-between align-items-center background-color--white pointer--cursor&quot;]/div[@class=&quot;ss-dashboard__list-item--left col-12 col-xl-5 pe-0 pe-xl-5&quot;]/div[@class=&quot;d-flex align-items-center flex-wrap flex-md-nowrap&quot;]/div[@class=&quot;d-flex flex-column ss-dashboard__list-item--left-desc mt-3 mt-xl-0&quot;]/h3[@class=&quot;ss-text ss-text__size--h3 ss-text__weight--semibold ss-text__color--black mb--xs ss-text__overflow-wrap&quot;]</value>
      <webElementGuid>40a52018-5ce7-4f4c-8a30-7935546483b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div[2]/div/div/div[4]/div/div/div[3]/h3</value>
      <webElementGuid>deced6c8-3b54-4e47-95d5-78bb922124f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completion Rate'])[3]/following::h3[1]</value>
      <webElementGuid>3068583a-5dbf-4099-b519-cd74bd9506c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[3]/following::h3[1]</value>
      <webElementGuid>30d7ecf6-ae51-4e2f-bbf3-a40c1a30da16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[4]/preceding::h3[2]</value>
      <webElementGuid>6242453f-7f36-46cb-997c-b1e961a90313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automated CSAT Chat Survey Created on 20...']/parent::*</value>
      <webElementGuid>e55f10a0-3125-4579-b2e6-497eed88c607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/h3</value>
      <webElementGuid>96e4934f-c0e4-46dd-9313-3af99ac33dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Automated CSAT Chat Survey Created on 20...' or . = 'Automated CSAT Chat Survey Created on 20...')]</value>
      <webElementGuid>bf23c8a3-7a5b-421b-80ae-602372af2eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
