<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Delete</name>
   <tag></tag>
   <elementGuidId>eb88454e-d16f-49b3-8db2-fa2443eb0cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.ss-text.ss-text__size--h4.ss-text__weight--semibold.ss-text__color--red.ms-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ss-drop-menu-90']/li[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f6a49e51-07e7-46e8-8003-a291cbe44068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-text ss-text__size--h4 ss-text__weight--semibold ss-text__color--red ms-4</value>
      <webElementGuid>f8f2b11b-6c54-42bc-9504-e52915788896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>019105b6-6c27-4e8e-8403-610d27ff280b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--csat-chat fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-dashboard--wrapper d-flex w-100&quot;]/div[@class=&quot;fx-grow-1 h-100&quot;]/div[@class=&quot;ss-container--scrollable ss-nps-active-share-table ss-share-distribution&quot;]/div[@class=&quot;grid h-100&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;grid grid-nogutter ss-animate--fadeIn mt--xl&quot;]/div[@class=&quot;col-12&quot;]/div[1]/div[@class=&quot;ss-share-distribution__item  d-flex flex-column mb-4 shadow-1&quot;]/div[@class=&quot;row py-3&quot;]/div[@class=&quot;col-5&quot;]/div[@class=&quot;d-flex w-100 h-100 align-items-center justify-content-between&quot;]/div[@class=&quot;ss-share-distribution__item--controls d-flex align-items-center pe-3&quot;]/div[@class=&quot;ss-share-distribution__channel-more-options&quot;]/div[@class=&quot;ss-button--dropdown ss-button--dropdown--open&quot;]/ul[@id=&quot;ss-drop-menu-90&quot;]/li[2]/div[@class=&quot;w-100 d-flex align-items-center&quot;]/h4[@class=&quot;ss-text ss-text__size--h4 ss-text__weight--semibold ss-text__color--red ms-4&quot;]</value>
      <webElementGuid>16e408cf-1729-411d-a39b-8229346fff1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ss-drop-menu-90']/li[2]/div/h4</value>
      <webElementGuid>ca563d7c-69fe-4969-adbf-17b82193cf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::h4[1]</value>
      <webElementGuid>9ca15836-f2c6-4a5b-9569-7924ff97f229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next: 10 July 2023 04:48 AM'])[1]/following::h4[2]</value>
      <webElementGuid>4e2b0bf6-0e42-4100-827a-d08ac7a95a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>83e1fc9b-89e1-45b6-bfdb-8c9a5aba449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/h4</value>
      <webElementGuid>facc7bd9-1759-46f9-b8b7-309429684f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>8cba449b-7d1f-46f2-994c-5000bf018900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
