<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Profile_ss-icon-plus_round</name>
   <tag></tag>
   <elementGuidId>8c691714-8685-4b9f-b454-8b2111a14e0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2022f037-87c3-400a-93b5-ebbe4bd19c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-icon-plus_round  </value>
      <webElementGuid>664fae7b-e36a-49af-b5db-f19defd9b6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>122c3937-8b66-43e6-aa10-1797d046f647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--classic fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-builder--wrapper fx-row fx-ai--stretch&quot;]/div[@class=&quot;left_sidebar sidebar_builder border-right&quot;]/div[@class=&quot;left_sidebar_content c_gp1&quot;]/div[@class=&quot;left_sidebar_section&quot;]/div[@class=&quot;ss-builder-add-new ss-builder-add-new--sm-sidebar-card&quot;]/div[@class=&quot;icon-wrapper&quot;]/i[@class=&quot;ss-icon-plus_round&quot;]</value>
      <webElementGuid>a202e27a-fcab-4d5a-afdc-41e464ff0dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div/div/div/div/i</value>
      <webElementGuid>b0d2f464-5545-4e40-ab99-9a4de090de76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>f1b66bea-2f15-483f-bca5-82c7638b37b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
