<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Reply STOP to opt-out. MsgDataRatesMa_9ad4c3</name>
   <tag></tag>
   <elementGuidId>5df63a18-3fe7-4e2e-91eb-fb6e71017a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.checkmeout-checkbox-style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c67accf2-59b5-481a-84e5-b6f883a3b6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmeout-checkbox-style</value>
      <webElementGuid>f2ce1209-b286-412a-9385-827be3f9eca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>51f6b03e-111a-41a1-b30c-ed0fa42f683d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--csat-chat fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-share--wrapper fx-row fx-jc--center&quot;]/div[@class=&quot;ss-share--container fx-row fx-ai--stretch fx-as--center mt--auto mb--auto&quot;]/div[@class=&quot;ss-share-preview--wrapper&quot;]/div[@class=&quot;fx-row pt-4&quot;]/div[@class=&quot;fx-row&quot;]/div[@class=&quot;checkmeout-checkbox checkmeout-checkbox-sm&quot;]/label[@class=&quot;checkmeout-checkbox-style&quot;]</value>
      <webElementGuid>1d9dfb90-c552-4e08-b3fc-edf7cd8f1b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div/label</value>
      <webElementGuid>6ab9eeb1-bb05-4737-9ca5-78725ab9b0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>d4bdc23a-0949-4441-b3ef-581c70426518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
