<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Logout</name>
   <tag></tag>
   <elementGuidId>3a657cab-c096-44f0-8b20-b8a416405951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tracking-navbar__profile--logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tracking-navbar__profile--logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8f959960-c092-4d5a-9e6e-4f040df8c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tracking-navbar__profile--logout</value>
      <webElementGuid>aec6faa0-3bde-4c45-bee5-438c98600678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fx-row</value>
      <webElementGuid>f53c1570-68bc-4ec4-9806-a67ec5b9a232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>1c99c4e9-2dce-40a7-b20a-79f4d087936b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tracking-navbar__profile--logout&quot;)</value>
      <webElementGuid>43087b88-c0cb-4066-9113-ed3cd08f70dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='tracking-navbar__profile--logout']</value>
      <webElementGuid>c71bb930-b4e4-4bb7-91bf-d215b15a9529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ss-drop-menu-16']/li[4]</value>
      <webElementGuid>f82e4f2e-2df8-4adb-a41f-0443a421629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referrals'])[1]/following::li[1]</value>
      <webElementGuid>c1a92176-589e-43df-a795-bab1cd6b78ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to Portal'])[1]/following::li[2]</value>
      <webElementGuid>f4d5e32c-f3b6-49bb-a078-b93fb4ca2541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[1]/preceding::li[1]</value>
      <webElementGuid>ca76526e-834d-49ad-928a-c772e0942b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Surveys (3)'])[1]/preceding::li[1]</value>
      <webElementGuid>d5344630-f8f4-4285-a80c-c73994f592c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>23e5fa6d-8d4a-45fb-91b1-46de6912cae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]</value>
      <webElementGuid>e593a87b-87bb-4e98-a994-e0b04f1c8d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'tracking-navbar__profile--logout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>1b8857dc-ef19-4be3-bb9e-cc00cc69614d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
