<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Learn more_choices</name>
   <tag></tag>
   <elementGuidId>3fb1355e-6380-467f-b4d5-be1738200317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choices</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='choices']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5180d00b-5c88-4647-a522-444c67f4d9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-form--input ss-form--input--textarea</value>
      <webElementGuid>620d0160-1454-4aec-9c7b-180db83c4882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>da02bb47-92ac-4910-8255-41a730959b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choices</value>
      <webElementGuid>6d2a1bee-47f1-4d70-8e3e-a626e16f276e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices</value>
      <webElementGuid>63c2d807-64f1-4710-8f11-b6b3997170ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices&quot;)</value>
      <webElementGuid>c773ddcf-18c3-46ce-8c86-40e9363ffcb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='choices']</value>
      <webElementGuid>dfd38fa4-47a2-46a9-a849-a9ceb0e3196a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div[2]/div[2]/div[2]/div/textarea</value>
      <webElementGuid>d9ded1c5-f486-4749-9f68-921819f8f0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>b33e74ee-c13f-4a29-ba1f-3c60f93625fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'choices' and @id = 'choices']</value>
      <webElementGuid>6b465285-1607-4a3e-bd64-1be86bc66bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
