<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_mp 3KEYC</name>
   <tag></tag>
   <elementGuidId>652127ec-7353-4aed-bedf-a6f2ec251df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='mc-1000186736'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>936bd652-0ad5-47c1-86a9-2dddd5f56419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1fbb28c4-cbeb-485a-ad60-af4302e6f59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-answer-option--choice ss-answer-option--bg ss-answer-option--border ss-answer-option--text-light ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--sm ss-survey-line-height--tight ss-survey-text-weight--regular ss-survey-text-color--secondary ss-answer-item--has-key-assist</value>
      <webElementGuid>f865b314-4e62-4014-8d98-fd5cedce0e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>option_2</value>
      <webElementGuid>cf81bb5c-6049-4e2c-8c12-307c075c385a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hotkey-refkey</name>
      <type>Main</type>
      <value>hotkey-item-C</value>
      <webElementGuid>b5fae20d-514b-47e4-95ef-ee1cc54b2352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hotkey-value</name>
      <type>Main</type>
      <value>1000244760</value>
      <webElementGuid>68e2c110-bdc7-4fcf-b8c2-c5442450fc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a8ce4366-2f0e-4a31-9e81-24558a553fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mc-1000186736</value>
      <webElementGuid>6024024e-a6e6-442b-a04d-b4cbdd7c1e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14f76b6f-95a2-450a-ab13-01d867cc88ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mp 3KEYC</value>
      <webElementGuid>1f980d7c-c9ad-4482-8336-ac52329829be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000186736&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_options_container&quot;]/div[@class=&quot;ss_multiple_choice ss_component_animated&quot;]/button[@class=&quot;ss-answer-option--choice ss-answer-option--bg ss-answer-option--border ss-answer-option--text-light ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--sm ss-survey-line-height--tight ss-survey-text-weight--regular ss-survey-text-color--secondary ss-answer-item--has-key-assist&quot;]</value>
      <webElementGuid>6b7949b2-bbde-4871-8ecd-0e4a4048a0db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='mc-1000186736'])[3]</value>
      <webElementGuid>6292216d-0c9a-4590-9fec-a12cf0fdfd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000186736']/span/div/div/button[3]</value>
      <webElementGuid>101ae62e-0bfd-410a-84bb-350218bf484c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/following::button[1]</value>
      <webElementGuid>2d098f30-2c18-41e1-9cc1-75347ea4d56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEY'])[2]/following::button[1]</value>
      <webElementGuid>99b2f6b6-355f-472f-be24-2b2e479d6f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>a26c9e2c-1d91-4b55-8a99-2d248c413a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'mc-1000186736' and (text() = 'mp 3KEYC' or . = 'mp 3KEYC')]</value>
      <webElementGuid>8c1a7be7-f341-4c28-9a2f-788670e1990c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
