<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>b97d0eaf-400b-4841-b39c-85572f16cbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ss-primary-action-btn.ss-survey-font-family.ss-survey-text-size--base.sm_ss-survey-text-size--base.ss-survey-line-height--tight.ss-survey-text-weight--bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question_1000186739']/span/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5b6089c-be45-4d50-bb74-bb743c2b9326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>next_button</value>
      <webElementGuid>185092c8-8355-4184-95ad-f80d6bd26e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hotkey-item</name>
      <type>Main</type>
      <value>hotkey-cta-button</value>
      <webElementGuid>c5aff634-12c1-4aee-94ef-ede932712951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-primary-action-btn ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--base ss-survey-line-height--tight ss-survey-text-weight--bold</value>
      <webElementGuid>08ea2485-cbb7-4d40-9352-ddf235cbbdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>59a5debb-a0e0-4e67-a0b6-6f5931101392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000186739&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_cl_qstn_action&quot;]/div[1]/button[@class=&quot;ss-primary-action-btn ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--base ss-survey-line-height--tight ss-survey-text-weight--bold&quot;]</value>
      <webElementGuid>f42c70ea-9f2e-494f-91db-013f1737d8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000186739']/span/div[2]/div/button</value>
      <webElementGuid>f57df1c6-c9f7-4888-8bf3-533c4d45fd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Question'])[1]/following::button[1]</value>
      <webElementGuid>90cf0830-d590-47d3-b42e-ddd705ec2096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip'])[1]/preceding::button[1]</value>
      <webElementGuid>e08585c8-af00-4f5a-a76c-2346953aabfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d6483f4c-c425-4f92-84a3-8a02a4cb3d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>4aae14f8-3103-4ed0-96cd-dd6d94f48c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
