<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>5292cb98-ed9d-4996-b101-71c216ebde40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ss-primary-action-btn.ss-survey-font-family.ss-survey-text-size--base.sm_ss-survey-text-size--base.ss-survey-line-height--tight.ss-survey-text-weight--bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question_1000186740']/span/div[2]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>179467ee-894c-4eb4-8f1f-91d1db5c6ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>submit_button</value>
      <webElementGuid>c6d1ff74-fbec-4ad8-a442-1f112908d0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-primary-action-btn ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--base ss-survey-line-height--tight ss-survey-text-weight--bold</value>
      <webElementGuid>f024c6ec-9695-4728-b855-f1a004031169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>0df11b2a-52c5-4069-b973-477f63886dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000186740&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_cl_qstn_action&quot;]/div[@class=&quot;active&quot;]/div[@class=&quot;ss_cl_survey_submit_resp&quot;]/div[@class=&quot;ss_cl_survey_submit_resp_btn_wrapper&quot;]/button[@class=&quot;ss-primary-action-btn ss-survey-font-family ss-survey-text-size--base sm_ss-survey-text-size--base ss-survey-line-height--tight ss-survey-text-weight--bold&quot;]</value>
      <webElementGuid>0cf455bb-20f4-436d-b0c4-8e35ec46a452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000186740']/span/div[2]/div/div/div/button</value>
      <webElementGuid>4d9993b3-74d6-46b4-ba31-1864651e66fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Question'])[1]/following::button[1]</value>
      <webElementGuid>221b972c-6bd5-4545-9781-06f3e9291e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTER'])[1]/preceding::button[1]</value>
      <webElementGuid>eb5493bc-b0d2-4d00-9a1c-2a80705b5f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9ae2222d-ff13-49dc-bd83-44ae200ce654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>f37a557e-962e-46aa-b441-a5f6308d5341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
