<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Question_answer-option--input s_862325</name>
   <tag></tag>
   <elementGuidId>ccbfcfc7-c6f8-434e-b719-c00e51d0af9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.answer-option--input.ss-survey-font-family.ss-survey-text-size--2xl.sm_ss-survey-text-size--lg.ss-survey-line-height--tight.ss-survey-text-weight--regular.ss-survey-border-style--solid.ss-survey-border-color--primary.ss-survey-text-color--secondary.answer-option--input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6637cdd1-4aab-48d5-9c69-7b891401d52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8c5ca5f6-878d-47a8-8325-e100ddd49045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>99e10a53-aea7-44a2-b436-5cd4d05e54ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer-option--input ss-survey-font-family ss-survey-text-size--2xl sm_ss-survey-text-size--lg ss-survey-line-height--tight ss-survey-text-weight--regular ss-survey-border-style--solid ss-survey-border-color--primary  ss-survey-text-color--secondary answer-option--input</value>
      <webElementGuid>1c0c53d5-e177-4a09-85be-60fd006d55f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter an email</value>
      <webElementGuid>477bd591-03fe-4d92-b0aa-b363651c9687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>948ce901-4a1f-4f32-baa7-b8f42b29df77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>question-title-1000186740</value>
      <webElementGuid>cbe0e22f-0fb6-426f-9591-156db871b630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>question-title-1000186740 question-description-1000186740</value>
      <webElementGuid>0952c01d-a6b7-4221-b311-732ef82e54b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question_1000186740&quot;)/span[@class=&quot;ss_span_wrapper&quot;]/div[@class=&quot;ss_options_container&quot;]/div[@class=&quot;ss_inline_input_container ss_component_animated ss-form-group ss-form-group--lg-col-6&quot;]/input[@class=&quot;answer-option--input ss-survey-font-family ss-survey-text-size--2xl sm_ss-survey-text-size--lg ss-survey-line-height--tight ss-survey-text-weight--regular ss-survey-border-style--solid ss-survey-border-color--primary  ss-survey-text-color--secondary answer-option--input&quot;]</value>
      <webElementGuid>f3e1331c-f6de-43da-ab7d-13b0cbff79bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>3945db96-fffe-4832-88bc-5da544489fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question_1000186740']/span/div/div/input</value>
      <webElementGuid>5a5a3a52-a98d-4871-8ea9-743fc099545c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6d59252b-9532-4da0-8776-e1944212cc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Please enter an email']</value>
      <webElementGuid>550fe61e-9dad-4462-a798-4c7d000aa3ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
