<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>My_Surveys</name>
   <tag></tag>
   <elementGuidId>c281c0cf-0e8c-4acc-9c32-252f6c356d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.ss-text.ss-text__size--h2.ss-text__weight--semibold.ss-text__color--black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4402c201-6f62-4c45-806b-4ad69795b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-text ss-text__size--h2 ss-text__weight--semibold ss-text__color--black</value>
      <webElementGuid>dcb348dc-47e1-4b83-aea3-4c54ee0df143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Surveys</value>
      <webElementGuid>06656df0-74b7-4421-aae1-cdece74b1991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper ss-main-wrapper--fixed-scrolling&quot;]/div[@class=&quot;ss-dashboard--wrapper fx-row fx-ai--stretch bg-grey-7 ss-upgradebar--active&quot;]/div[@class=&quot;ss-dashboard--container fx--fh fx-grow-1 fx-column pt-5 pt-xl-6&quot;]/div[@class=&quot;ss-dashboard-home--wrapper&quot;]/div[@class=&quot;grid grid-nogutter ss-dashboard--header wplr--md py-0 px-5 px-xl-11 mb-5 mb-xl-6 fx-row fx-jc--between&quot;]/div[@class=&quot;fx-row fx-ai--center ss-dashboard--header-contents position-relative&quot;]/h2[@class=&quot;ss-text ss-text__size--h2 ss-text__weight--semibold ss-text__color--black&quot;]</value>
      <webElementGuid>d9c647f2-1a53-4aab-9a8b-2288487efa3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[3]/div[2]/div/div/div/h2</value>
      <webElementGuid>79d557bf-e3f2-4fe2-9c5b-7dc4bc1f2ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General (17)'])[1]/following::h2[1]</value>
      <webElementGuid>9845f782-c271-4d60-8921-2b42ecb40967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shared (0)'])[1]/following::h2[1]</value>
      <webElementGuid>349dc268-39e9-4a04-bf28-9015072ca53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Filter'])[1]/preceding::h2[1]</value>
      <webElementGuid>42ce82a1-761c-46ff-a8c2-87b34995dd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently Updated'])[1]/preceding::h2[1]</value>
      <webElementGuid>0f647f37-3b20-446c-b1e6-fd3ec69c4222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>4f5ce98a-b353-431c-bd48-b39d5653580d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'My Surveys' or . = 'My Surveys')]</value>
      <webElementGuid>641f7ec8-5e05-4bd4-b2bc-3c91dfc99621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
