<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome Page</name>
   <tag></tag>
   <elementGuidId>8aa564a5-219d-4348-9011-6e2adac75238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22e973c7-d459-401c-9f27-aed9efe457e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC</value>
      <webElementGuid>f3474141-f945-4bc4-b1c1-1bf9ff0c115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-question-item ss-question-item--highlight ss-question-item--welcome</value>
      <webElementGuid>8b17f541-b89d-4950-ba7c-0ef449926727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9fbe85d5-f9ea-4997-8651-acf30d1a7a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome Page</value>
      <webElementGuid>0c117677-41c9-4efc-b537-2cec0e06e341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC&quot;)</value>
      <webElementGuid>419ae53a-169f-4f40-8272-173e9ccfb9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='WC']</value>
      <webElementGuid>277d8a55-3919-491c-8217-101afd67657c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/span/div</value>
      <webElementGuid>aaa683d5-2ba0-433f-96b3-882b3eade5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[19]</value>
      <webElementGuid>cf4e9e7e-c24d-4e36-9f48-d95881035b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[19]</value>
      <webElementGuid>393ab80c-ab6d-48ff-b1bf-b52e23c23e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Used'])[1]/preceding::div[1]</value>
      <webElementGuid>ac6b2f57-5772-4f8b-b88a-45b4442a4596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/div</value>
      <webElementGuid>6bddb417-7725-43a4-9bfa-29c399e525d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'WC' and (text() = 'Welcome Page' or . = 'Welcome Page')]</value>
      <webElementGuid>ee91a9a7-8fa5-41a1-a2db-048da00e3353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
