<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hi.Hello.Hola.Hey</name>
   <tag></tag>
   <elementGuidId>9d0506be-fc8c-4538-886c-be0e4ea1b15f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qcontainer']/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.public-DraftStyleDefault-block.public-DraftStyleDefault-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9adb881-b4b0-465f-80d4-2c9ad5a03be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-key</name>
      <type>Main</type>
      <value>1hern-0-0</value>
      <webElementGuid>b66918b9-6113-4d0c-8a1e-13e3a1f0fad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>public-DraftStyleDefault-block public-DraftStyleDefault-ltr</value>
      <webElementGuid>9040cb30-fb13-41bb-b8ec-8851687bcba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi.Hello.Hola.Hey.</value>
      <webElementGuid>799d7aea-ee2d-411c-b650-2784336d6732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qcontainer&quot;)/div[1]/div[@class=&quot;DraftEditor-root&quot;]/div[@class=&quot;DraftEditor-editorContainer&quot;]/div[@class=&quot;notranslate public-DraftEditor-content&quot;]/div[1]/div[1]/div[@class=&quot;public-DraftStyleDefault-block public-DraftStyleDefault-ltr&quot;]</value>
      <webElementGuid>898a2689-b5eb-4114-b937-fe07e9a9f71f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qcontainer']/div/div/div/div/div/div/div</value>
      <webElementGuid>3610140e-ea21-497d-a327-0cefd04f03b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::div[16]</value>
      <webElementGuid>f5b35653-760e-45ae-97fb-a5a02129e97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::div[16]</value>
      <webElementGuid>89bd5b34-6ae6-45e8-b27e-e965ac73b38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got a moment to share some feedback?'])[1]/preceding::div[8]</value>
      <webElementGuid>baf1b377-cf94-4c31-8c1c-aa771456dd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>2b0f6f89-a9e7-49d8-aafa-fb5dbaab96f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hi.Hello.Hola.Hey.' or . = 'Hi.Hello.Hola.Hey.')]</value>
      <webElementGuid>34a39bfc-d902-4609-a90d-5ffe168f0aa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
