<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank You Page</name>
   <tag></tag>
   <elementGuidId>11388d96-1f49-47a9-bb9d-319da8ea3ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43f26c3b-49d6-4fa2-aaf6-84ce87aea1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TY</value>
      <webElementGuid>d378e082-621d-4e71-9920-1b85e96251b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-question-item--thank-you ss-question-item ss-question-item--highlight</value>
      <webElementGuid>c3b854b6-79ad-4c9d-a183-6791139eadac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>229dabae-2dd6-4e04-b60c-529c64455621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank You Page</value>
      <webElementGuid>61ebbcd3-fd7b-498c-b809-f3d14be818cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TY&quot;)</value>
      <webElementGuid>6187a52c-49e9-4026-9cb1-8c729707f612</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='TY']</value>
      <webElementGuid>bcc65ea2-e2f7-4bdc-b030-1f622d4ca26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div[3]/span/div</value>
      <webElementGuid>906907cb-5527-4c86-b730-a4b03bd3cf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Rating'])[1]/following::div[2]</value>
      <webElementGuid>5884a4c2-aae0-4b09-a000-c51f9ae77085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Capture'])[1]/following::div[4]</value>
      <webElementGuid>37e25952-b973-445d-b240-b89293f81caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'TY', '&quot;', ')')])[1]/preceding::div[3]</value>
      <webElementGuid>bdfc2fea-7278-4604-ad4d-fcc962e313d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/div</value>
      <webElementGuid>14711a96-c2a9-4466-a621-7a21a3be2424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'TY' and (text() = 'Thank You Page' or . = 'Thank You Page')]</value>
      <webElementGuid>b53425ac-b93c-44c2-9b7c-cfb5f9f8c809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
