<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Classic Survey</name>
   <tag></tag>
   <elementGuidId>f201f383-897d-44c1-bf06-ed256b95c179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newClassicSurvey']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>786ca71a-d7e3-4400-b968-5d4310e8956f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-10</value>
      <webElementGuid>3318cc13-9993-4bd7-b23d-35b9ca4a03a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classic Survey</value>
      <webElementGuid>24b30fbe-36da-41ed-957c-9a506d6a372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newClassicSurvey&quot;)/div[@class=&quot;col-10&quot;]</value>
      <webElementGuid>12366301-02ca-44be-80e6-b7c0d192fcac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newClassicSurvey']/div[2]</value>
      <webElementGuid>51cd171e-3308-4d8c-8811-6c725ab1954e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or, build your own'])[1]/following::div[4]</value>
      <webElementGuid>cfa961c2-a697-4dd2-814c-6fa56fb04950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create surveys in a jiffy with AI'])[1]/following::div[6]</value>
      <webElementGuid>ea5b416d-6e62-477e-b1eb-8b7e4dd702a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Survey'])[1]/preceding::div[2]</value>
      <webElementGuid>6f9d3747-3210-4316-8d8d-0d790d17c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]/div[2]</value>
      <webElementGuid>bb820a5f-d07b-4b22-982a-eab0097cb835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Classic Survey' or . = 'Classic Survey')]</value>
      <webElementGuid>72fe0103-bb3f-4008-8af8-de0c5549b90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
