<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click here to upload a welcome imageHi._699fda</name>
   <tag></tag>
   <elementGuidId>775cbc0d-fcc4-4337-97c0-e96ad87a521c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings']/div/span/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ss_chat.ss_bot.active.c_chat_txt_welcome.ss-question-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35c5cd72-e15f-4545-bbfb-8aa6552ec275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss_chat ss_bot active c_chat_txt_welcome ss-question-wrapper</value>
      <webElementGuid>088659ba-30bb-4a4b-87bc-f20662e11925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to upload a welcome imageHi.Hello.Hola.Hey.</value>
      <webElementGuid>bbeb4b64-8ed0-4052-b4a9-27867ae291b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings&quot;)/div[@class=&quot;c_builder_contents&quot;]/span[@class=&quot;ss_builder_container&quot;]/span[@class=&quot;ss_content_wrapper&quot;]/div[@class=&quot;ss_row--builder&quot;]/div[@class=&quot;ss_chat ss_bot active c_chat_txt_welcome ss-question-wrapper&quot;]</value>
      <webElementGuid>76a17697-6ddb-420e-9e7c-f23451ebe07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings']/div/span/span/div/div</value>
      <webElementGuid>fc4b9bd8-a908-48c2-8452-623098fa59df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::div[4]</value>
      <webElementGuid>35217c5a-fdbe-442e-b6f0-923f24549ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::div[4]</value>
      <webElementGuid>07b9c7b1-0953-40de-a660-e46f10550458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got a moment to share some feedback?'])[1]/preceding::div[20]</value>
      <webElementGuid>50db0873-7ec5-45a5-ae90-cc2aed0dc402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>8ba4580f-6c5e-4328-b73c-8660c6d12d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Click here to upload a welcome imageHi.Hello.Hola.Hey.' or . = 'Click here to upload a welcome imageHi.Hello.Hola.Hey.')]</value>
      <webElementGuid>e70a4e18-3f7e-4582-b509-75702646516f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
