<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Default Report</name>
   <tag></tag>
   <elementGuidId>11a11e27-9246-44e0-ab5c-0397dc7623f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reportItemCover']/div[3]/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.ss-text.ss-text__size--jumbo.ss-text__weight--bold.ss-text__color--black.ss-text__family--serif.ss-text__overflow-wrap.mb--sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>610a22d3-713c-442b-9178-fea97b189e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-text ss-text__size--jumbo ss-text__weight--bold ss-text__color--black ss-text__family--serif ss-text__overflow-wrap mb--sm</value>
      <webElementGuid>4755f6be-deb5-4fec-997e-0008b34fe950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default Report</value>
      <webElementGuid>a6069671-3f80-46b9-9fba-d096f272026f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportItemCover&quot;)/div[@class=&quot;ss-reports--cover-info&quot;]/h1[@class=&quot;ss-text ss-text__size--jumbo ss-text__weight--bold ss-text__color--black ss-text__family--serif ss-text__overflow-wrap mb--sm&quot;]</value>
      <webElementGuid>0e88fce4-e5f0-4759-8084-1d29c047ab44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reportItemCover']/div[3]/h1</value>
      <webElementGuid>e30bc8f6-936c-4a56-8b6c-8c283dbb565e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_Automation'])[1]/following::h1[1]</value>
      <webElementGuid>b7af6f28-219c-4285-9cfc-57f6fe419ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visited'])[1]/preceding::h1[1]</value>
      <webElementGuid>2f3b8585-66d6-4514-ad5a-7dfb112c2db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Started'])[1]/preceding::h1[2]</value>
      <webElementGuid>e3f7b87f-b150-4438-beeb-98fd71581f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>5913911b-bc20-474c-957e-6a1ad2bef223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Default Report' or . = 'Default Report')]</value>
      <webElementGuid>199b0d42-7138-47d7-a9e6-fca28efa07a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
