<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_100</name>
   <tag></tag>
   <elementGuidId>a5682352-09c0-42dd-8dc7-c797b53da14c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.ss-responses-insights__radial-percentage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1a57b7de-00f4-4bac-b66b-d5026a228fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-responses-insights__radial-percentage</value>
      <webElementGuid>2d776f5e-8fb3-4bf2-b95f-f1302e5227e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3b52cc19-9c08-444f-866f-b2f6240b8611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--classic fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-responses-overview--wrapper px-0 pb-0&quot;]/div[@class=&quot;background-color--grey wptb--lg ss-dashboard-main-data&quot;]/div[@class=&quot;ss-main-container ss-nps-reports-dashboard&quot;]/div[@class=&quot;d-flex flex-column demo--fixed-height&quot;]/div[@class=&quot;ss-responses-insights d-flex px-6 py-7&quot;]/div[@class=&quot;row w-100 ss-responses-insights__container&quot;]/div[@class=&quot;ss-responses-insights__right col-2 pt-2&quot;]/div[@class=&quot;ss-responses-insights__right-content&quot;]/div[@class=&quot;ss-responses-insights__radial-container fx--fw fx-ai--center fx-jc--center fx-row&quot;]/div[@class=&quot;ss-responses-insights__radial mt--lg&quot;]/h2[@class=&quot;ss-responses-insights__radial-percentage&quot;]</value>
      <webElementGuid>8439b6aa-5089-4a4e-93fb-3ef143607bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div[2]/div/h2</value>
      <webElementGuid>667f2cd5-da51-45cc-9397-28ad582fd35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completion Rate'])[1]/following::h2[1]</value>
      <webElementGuid>1743223d-22a8-4dcc-8166-2e4a56eeef6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/following::h2[2]</value>
      <webElementGuid>99d37b63-987f-4706-be87-7e6208a056e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[2]/preceding::h2[1]</value>
      <webElementGuid>8673f486-7b37-47b9-af7e-cce341667d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Device'])[1]/preceding::h2[1]</value>
      <webElementGuid>8d5bbc35-f41c-4c2a-82a8-fb1416ec6e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100']/parent::*</value>
      <webElementGuid>7189bb7e-add4-4020-8d2d-d18fb2af5e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>51478833-e177-4f5d-8b8b-9f7d995566ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '100%' or . = '100%')]</value>
      <webElementGuid>75cf7909-c9a7-45e5-9948-2fb90b6351ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
