<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Profile_ss-icon-plus_round</name>
   <tag></tag>
   <elementGuidId>1bcc09af-6880-4a56-9f8e-a2914d21095e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div/div/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bb7c6413-87ac-4c3c-a91a-471c0db228ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-icon-plus_round  </value>
      <webElementGuid>333a8f3e-5354-49bf-bc05-461bf1fec561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b73ebb5-edfb-4f91-a460-6714a7bccf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--classic fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-builder--wrapper fx-row fx-ai--stretch&quot;]/div[@class=&quot;left_sidebar sidebar_builder border-right&quot;]/div[@class=&quot;left_sidebar_content c_gp1&quot;]/div[@class=&quot;left_sidebar_section&quot;]/div[@class=&quot;ss-builder-add-new ss-builder-add-new--sm-sidebar-card&quot;]/div[@class=&quot;icon-wrapper&quot;]/i[@class=&quot;ss-icon-plus_round&quot;]</value>
      <webElementGuid>7a567e94-bae8-44b0-8597-1ac37073257b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div/div/div[2]/div[2]/div/div/div/div/div/div/i</value>
      <webElementGuid>c39eb6a8-83d7-4a51-b8b2-7b3af1689dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>af2634e7-3a17-4e9c-99b8-e2faa005d2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
