<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Survey Title_ss-form--input</name>
   <tag></tag>
   <elementGuidId>d8ae26cf-6649-4d15-b09c-1bd26c96fc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ptb--lg.wplr--sm > div.flex_column.ss-form--input-group > div.fx-row.fx-ai--stretch.fx--fw > input.ss-form--input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f17f0a1-7fd6-46d7-93c8-04ac6d3210f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-form--input</value>
      <webElementGuid>557bc4cf-1b1b-4a24-953e-f7945bd5fb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f584d58-7f34-4925-a0f3-1992e8f2973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;ss-modal--wrapper ss-modal--wrapper__sm&quot;]/div[@class=&quot;ss-modal--container&quot;]/div[@class=&quot;ptb--lg wplr--sm&quot;]/div[@class=&quot;flex_column ss-form--input-group&quot;]/div[@class=&quot;fx-row fx-ai--stretch fx--fw&quot;]/input[@class=&quot;ss-form--input&quot;]</value>
      <webElementGuid>9293db2c-97cb-4445-8f71-ab50d3447004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>8baa4e4c-201b-4554-82a2-facc093e157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>49f8c728-a42a-4b0e-97d5-e1c0f2afbe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2aeb9ba9-f2f9-4dc3-b7a3-dd23dd8dcfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f6d1590a-960b-45db-9895-fe0bf9c4d98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
