<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_TOTAL RESPONSES_recharts-rectangle</name>
   <tag></tag>
   <elementGuidId>1f691ecf-96f1-479b-82e2-2ec7e84d5108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.recharts-rectangle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>4b465c92-d48e-49e9-bdfb-043488a3ee38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(0, 82, 204, 0.6)</value>
      <webElementGuid>17acf51c-3946-486d-89c0-2cb41b3856b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>radius</name>
      <type>Main</type>
      <value>3,3,0,0</value>
      <webElementGuid>8dcc7394-cdc6-4bb6-872d-dacff7e56d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>d4075262-e2bc-4917-910f-0276469c28ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>178</value>
      <webElementGuid>5030df09-08f1-4990-9476-ca56afb67dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>456.3</value>
      <webElementGuid>1985c58d-d26b-4283-b6c6-2e88e5aa2a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>1eb5cc2c-4b04-4754-9326-7b87cbe4964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recharts-rectangle</value>
      <webElementGuid>f16823b9-7531-49a4-8eb7-dd421d250690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M456.3,27A 3,3,0,0,1,459.3,24L 513.3,24A 3,3,0,0,1,
        516.3,27L 516.3,202L 456.3,202Z</value>
      <webElementGuid>7e3956d6-2fcf-44a5-83ac-3016d666c1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;grid grid-nogutter grid-nowrap&quot;]/div[@class=&quot;fx--fw ss-main-wrapper&quot;]/div[@class=&quot;wrapper--classic fx-row fx--fw fx-ai--start&quot;]/div[@class=&quot;fx-grow-1 mw-100&quot;]/div[@class=&quot;ss-responses-overview--wrapper px-0 pb-0&quot;]/div[@class=&quot;ss-main-container ss-nps-trend-container&quot;]/div[@class=&quot;ss-nps-trend-chart--container&quot;]/div[@class=&quot;ss-dashboard-trend-wrapper ss-dashboard-trend-wrapper--classic ss-nps-trend-chart--bottom my-12&quot;]/div[@class=&quot;recharts-responsive-container&quot;]/div[@class=&quot;recharts-wrapper&quot;]/svg[@class=&quot;recharts-surface&quot;]/g[@class=&quot;recharts-layer recharts-bar&quot;]/g[@class=&quot;recharts-layer recharts-bar-rectangles&quot;]/g[@class=&quot;recharts-layer&quot;]/g[@class=&quot;recharts-layer recharts-bar-rectangle&quot;]/path[@class=&quot;recharts-rectangle&quot;]</value>
      <webElementGuid>664f08c4-d7fd-4981-8eef-4ed1f0c97bf2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
