<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start Blank</name>
   <tag></tag>
   <elementGuidId>2a049f07-c77d-4d81-9bb2-f9a1abca9b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-container']/div[2]/div[2]/div/div[2]/div/div[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pr--xl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>886655ae-2f90-4a97-b557-a20e123d906f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pr--xl</value>
      <webElementGuid>b07fa8da-752b-49b5-874e-ffe062986149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Blank</value>
      <webElementGuid>0aa2b067-26ee-42d2-8872-ff88b87f8696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-container&quot;)/div[@class=&quot;ss-modal--wrapper ss-modal--wrapper__sm ss-modal--wrapper__lg ss-modal--wrapper__xs-full py-md-7 ss-modal--wrapper-new ss-modal--wrapper--no-close-btn&quot;]/div[@class=&quot;ss-modal--container ss-modal--wrapper-new__container&quot;]/div[@class=&quot;ss-new-survey-modal--wrapper d-flex align-items-stretch ss-new-survey-modal--wrapper-new&quot;]/div[@class=&quot;ss-new-survey-modal--right wp--lg&quot;]/div[@class=&quot;ss-new-survey-modal--classic&quot;]/div[@class=&quot;flex_row flex_row--row-mob flex_row--justify-center&quot;]/a[@class=&quot;ss-button ss-button__primary&quot;]/span[@class=&quot;pr--xl&quot;]</value>
      <webElementGuid>f26f8e52-c65f-42a6-8f3c-1cb42ace5a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-container']/div[2]/div[2]/div/div[2]/div/div[3]/a/span</value>
      <webElementGuid>a9aeb87c-0096-4998-a53b-f5bee25504aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used for creating surveys with complex question types.'])[1]/following::span[1]</value>
      <webElementGuid>c3018bf2-9986-42a4-93bd-ff4d6f8973bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a Classic Survey'])[1]/following::span[1]</value>
      <webElementGuid>86c36630-09b3-463b-89ee-5f3fadc4fff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Classic Templates'])[1]/preceding::span[1]</value>
      <webElementGuid>40c074c2-dbbe-4735-9339-e2c38273fbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Blank']/parent::*</value>
      <webElementGuid>3f8616de-c9f5-49ae-b916-7c2d8d56e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>3bed08a8-fa2f-407b-bbb4-ee3b12ed5771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Start Blank' or . = 'Start Blank')]</value>
      <webElementGuid>40639aa3-7d59-4b92-9e8c-9ad8726dfdac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
