<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hi.Hello.Hola.Hey</name>
   <tag></tag>
   <elementGuidId>812e1095-150c-4ae0-8581-816d3c041a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qcontainer']/div/div/div/div/div/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.public-DraftStyleDefault-block.public-DraftStyleDefault-ltr > span > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c24f5929-0040-4508-ba3c-14a8670a2411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44813b28-ff44-47f1-91fa-df118c46645c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi.Hello.Hola.Hey.</value>
      <webElementGuid>6daad01c-140e-4778-b3f8-14022f3fbf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qcontainer&quot;)/div[1]/div[@class=&quot;DraftEditor-root&quot;]/div[@class=&quot;DraftEditor-editorContainer&quot;]/div[@class=&quot;notranslate public-DraftEditor-content&quot;]/div[1]/div[1]/div[@class=&quot;public-DraftStyleDefault-block public-DraftStyleDefault-ltr&quot;]/span[1]/span[1]</value>
      <webElementGuid>d6172952-df21-4e89-9c5a-6e2c82608370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qcontainer']/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>3e876f70-9827-46ee-b1b0-f7ad512e306b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::span[4]</value>
      <webElementGuid>0078bdb9-3874-400d-8c98-a3d363732310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[4]</value>
      <webElementGuid>2f919b30-14ae-436d-a5ff-4403e9fba398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got a moment to share some feedback?'])[1]/preceding::span[1]</value>
      <webElementGuid>0b47072f-55a9-4d88-8013-812ea9cf070f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::span[1]</value>
      <webElementGuid>e8f4fdd5-49ba-4aa0-a492-f95cb17074a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>509abcfa-7139-44cd-9e9e-8ab71afb9d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hi.Hello.Hola.Hey.' or . = 'Hi.Hello.Hola.Hey.')]</value>
      <webElementGuid>e3190603-a67e-46b8-bab4-3c107b07e35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
